version: '2'
services:
  music-app:
    image: music
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://music-postgresql:5432/music
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://music-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://music-elasticsearch:9200
    ports:
      - 8080:8080
  music-postgresql:
    extends:
      file: postgresql.yml
      service: music-postgresql
  music-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: music-elasticsearch
